### ISSUE TITLE
Косметический ремонт

### ISSUE THREAD

**Issue by sergeygaychuk** [IgorIgor/abstract-accounting#2]
1. После создания объекта, переходить на страницу просмотра этого объекта.
2. Изменить логику отображения ресурса и места на отчете Балансы. Зависит от того кредит или дебит.  Проверить группировку.  Смотри реализацию with_resource | with_place.
3. Поправить главную книгу, дебет или кредит должны быть не ноль а значение txn. Смотри реализацию в бранче storage. Обратишься ко мне когда дойдешь до этой задачи.
4. При переходе по выпискам, выборка должна быть за тотже период.

Все это разбить на 3 коммита.

Время выполнения: 11 часов.

**Comment by IgorIgor** [comment]
выполнено за 13 часов
Сделал первый пункт своим способом, без перенесения ajaxJson в класс ObjectViewModel, а потом уже перенес его туда. Причем при вызове самого метода забыл отмапить параметры -> normalizeHash(ko.mapping.toJS(@object)), долго занимался поиском этого недочета.
Также возникли небольшие проблемы с формирование json как ответ от объектов о завершении операции и разбором json в яваскрипте.
Происходили странные вещи с тестами проверяющими Waybill.cancel, причем с Waybill.apply всё было в порядке. Было потрачено много времени пока не сошлись на том что достаточно что тесты пусть через раз но проходят.
В сделках валились тесты, "nil have no method tag" из-за неверных значений в базе данных, потому что give и take не могут быть nill, чего я не знал, и сделал проверку на nill, получил замечательный json со всеми данными и радовался, потом уточнил этот момент, пришлось заполнять базу заново.
